var links= {
	Rock: ["https://www.youtube.com/watch?v=L06x1Ee6Ct4&list=PL8a171akLsiksMqyYU-Scn8pgowwvzekx",
                        "https://www.youtube.com/watch?v=gu7j7g9Nt14&list=PL8a171akLsindd1Anaii_n8_7cijg6yR_",
                        "https://www.youtube.com/watch?v=t_Y4tLovYgY&list=PL8a171akLsikWu2Wqto845PnAUHjm6ml7",
                        "https://www.youtube.com/watch?v=Sb5aq5HcS1A&list=PL8a171akLsin0wcuBLH9K0tlX6CxTj-WY",
                        "https://www.youtube.com/watch?v=uPv0AOlTxXA&list=PL8a171akLsinUyFYSK9reF_n9R1cKBLn2",
                        "https://www.youtube.com/watch?v=0LFVQpDKHk4&list=PL8a171akLsinC6sV7BvYkVmLMc2vVV0ai",
                        "https://www.youtube.com/watch?v=eMqsWc8muj8&list=PL8a171akLsiml4D4B2E_IOQS7LN1WLZy2",
                        "https://www.youtube.com/watch?v=qddxDEsiSsQ&list=PL8a171akLsin-xb3PpqxMqjh7BVzJkNxR",
                        "https://www.youtube.com/watch?v=pkcJEvMcnEg&list=PL8a171akLsilDFz2uLC7Ehn3ZZes-tWLN",
                        "https://www.youtube.com/watch?v=n6P0SitRwy8&list=PL8a171akLsilt9o2CXSSmcStEVf-GEwY0"],
    Retro: ["https://www.youtube.com/watch?v=1pkVLqSaahk&list=PL8a171akLsikRr2whwyOTMDU1AWbrbQGU",
                        "https://www.youtube.com/watch?v=-2GmzyeeXnQ&list=PL8a171akLsinDQ5oSTay237Zhtj9b0syL",
                        "https://www.youtube.com/watch?v=WXQ86ZctKIY&list=PL8a171akLsimpR1SFNbk0BZSCzm0eDrOw",
                        "https://www.youtube.com/watch?v=VMnjF1O4eH0&list=PL8a171akLsimkRL6oH__t7HzoIydin736",
                        "https://www.youtube.com/watch?v=JiKgQYxUnTs&list=PL8a171akLsinnE1DZaVvSqFJBoqqIrZmX",
                        "https://www.youtube.com/watch?v=NWzeNnq1-rA&list=PL8a171akLsilLiQm22Q5c1ld2XF2BXbNN",
                        "https://www.youtube.com/watch?v=PtzgBJ13vro&list=PL8a171akLsinxlbc8kX34T5LjzyGVyiEK",
                        "https://www.youtube.com/watch?v=MR52MIJuZJY&list=PL8a171akLsinBC_6IGgfBRylnQkjvQoaq",
                        "https://www.youtube.com/watch?v=v_wLNqUz7pM&list=PL8a171akLsinnMjT86CBGPNLnUbf6v5dP",
                        "https://www.youtube.com/watch?v=F4DV-5d6a5g&list=PL8a171akLsillqozUlN4iF8jJ0mB0zFOF"],
    Sunshine: ["https://www.youtube.com/watch?v=RhmUnk454MA&list=PL8a171akLsikwccIhMm5FE-3IIA1KdluN",
                        "https://www.youtube.com/watch?v=YgSPaXgAdzE&list=PL8a171akLsikrbgOKz7KiTyIBdaaGbpCX",
                        "https://www.youtube.com/watch?v=_6Zp84XH6Eo&list=PL8a171akLsima9GoLkWd1fGRkba_2BiPr",
                        "https://www.youtube.com/watch?v=iJAorQM7sL8&list=PL8a171akLsimP2pxY0aKpgbHI_1E5L9Xx",
                        "https://www.youtube.com/watch?v=VkCg-3nxT8E&list=PL8a171akLsilLD8Uxc9ZVH4B1WuBx-Kpx",
                        "https://www.youtube.com/watch?v=jc5VCu0ECSI&list=PL8a171akLsimAz3Gju1hqTn0F3K0LiFOh",
                        "https://www.youtube.com/watch?v=32MBtTK-I1E&list=PL8a171akLsim4W4lSq50Rk0kVT3moouiO",
                        "https://www.youtube.com/watch?v=q2u5fDtggms&list=PL8a171akLsilXST2Ymwu3aofa3KrtaI9L",
                        "https://www.youtube.com/watch?v=ZJzJmUGx5oM&list=PL8a171akLsinjGwy_LT_M3a6ggUkSEH25",
                        "https://www.youtube.com/watch?v=STPN07RFmRc&list=PL8a171akLsin98nYfZFgj8fhLpxN4U4H3"],
    Coding: ["http://datashat.net/music_for_programming_1-datassette.mp3", 
                        "http://datashat.net/music_for_programming_4-com_truise.mp3",
                        "https://www.mixcloud.com/mixtapes4programming/i-need-my-spirituality-back/",
                        "http://datashat.net/music_for_programming_8-connectedness_locus.mp3",
                        "http://datashat.net/music_for_programming_11-miles_tilmann.mp3",
                        "http://datashat.net/music_for_programming_13-matt_whitehead.mp3",
                        "http://datashat.net/music_for_programming_15-dan_adeyemi.mp3",
                        "http://datashat.net/music_for_programming_18-konx_om_pax.mp3",
                        "http://datashat.net/music_for_programming_23-panda_magic.mp3",
                        "http://datashat.net/music_for_programming_28-big_war.mp3",
                        "http://datashat.net/music_for_programming_2-sunjammer.mp3",
                        "http://datashat.net/music_for_programming_9-datassette.mp3",
                        "http://datashat.net/music_for_programming_31-datassette.mp3",
                        "http://datashat.net/music_for_programming_30-matt_kruse.mp3",
                        "http://datashat.net/music_for_programming_24-rites.mp3",
                        "http://datashat.net/music_for_programming_16-silent_stelios.mp3",
                        "http://datashat.net/music_for_programming_20-uberdog.mp3",
                        "http://datashat.net/music_for_programming_25-_nono_.mp3",
                        "http://datashat.net/music_for_programming_22-mindaugaszq.mp3",
                        "http://datashat.net/music_for_programming_14-tahlhoff_garten_and_untitled.mp3"],
    Love: ["https://www.youtube.com/watch?v=xwtdhWltSIg&list=PL8a171akLsikTvboJQuXmhpCsfqQ8uGf-",
                        "https://www.youtube.com/watch?v=kea0ghm7Z4E&list=PL8a171akLsilBE5luUFb3YiVyOY5YpU1X",
                        "https://www.youtube.com/watch?v=ExLqMBLyWd8&list=PL8a171akLsilKT_tgObO0E_uvmIe3ScMb",
                        "https://www.youtube.com/watch?v=KSsW9ALDcKI&list=PL8a171akLsikE3TUtmqAqp7jMZrUxve8w",
                        "https://www.youtube.com/watch?v=oJu6vG64C2M&list=PL8a171akLsinmYsR8bpfTnszDU7Oi_KAR",
                        "https://www.youtube.com/watch?v=0vqgdSsfqPs&list=PL8a171akLsik8LrNPY0I5YbazgwCUKm2o",
                        "https://www.youtube.com/watch?v=Qx9br5ISRpo&list=PL8a171akLsimwkXDYVWpftxFYq6-jCaNL",
                        "https://www.youtube.com/watch?v=ycvJHQUqU1M&list=PL8a171akLsil_swGKFHUgfDU8LvGBDCkV",
                        "https://www.youtube.com/watch?v=BdHhsryzVbM&list=PL8a171akLsil1IwQ4dxt-KKc5OygkZV-u",
                        "https://www.youtube.com/watch?v=aPUjVt-CAbc&list=PL8a171akLsikQQlleYaNoFAkXGyWPM40b"],
    Relax: ["https://www.youtube.com/watch?v=WpfvJ3Jihy0&list=PLRUBalAzGf_eca_ME1rwKJRu3wOonCyl3",
                        "https://www.youtube.com/watch?v=W-fFHeTX70Q",
                        "https://www.youtube.com/watch?v=eBsW9SxCcwg",
                        "https://www.youtube.com/watch?v=qqt2jky4JNI",
                        "https://www.youtube.com/watch?v=VOOyTL3PhZQ&list=PLzQitc8xMvq6FbRgeUcxoHyamv6eQeVBn",
                        "https://www.youtube.com/watch?v=D1Ayd07KOxU&list=PL7AEE849A180DDF1A",
                        "https://www.youtube.com/watch?v=cOAZ7YoA63c",
                        "https://www.youtube.com/watch?v=Ziw4yd5R0QI",
                        "https://www.youtube.com/watch?v=YZKt_fDW85k",
                        "https://www.youtube.com/watch?v=wygy721nzRc"],
    Emo: ["https://www.youtube.com/watch?v=62i9Sodwp5o&list=PL8a171akLsinFu2ju6oPYuG1rYm5FPupF",
                    "https://www.youtube.com/watch?v=A9Tp5fl18Ho&list=PL8a171akLsimsgU6247MxRWuAL0JcZQ7m",
                    "https://www.youtube.com/watch?v=tZuC6y4eUo0&list=PL8a171akLsil2anN7_I8fltvaaYy6Y5G6",
                    "https://www.youtube.com/watch?v=T0yaQ20dpWI&list=PL8a171akLsikXsh8PDHuaS_8V7piW6Qd4",
                    "https://www.youtube.com/watch?v=4cOr7JmcOas&list=PL8a171akLsil3wAF2h8eUcBSGqNvoTB7j",
                    "https://www.youtube.com/watch?v=Mk8ijtUUf4w&list=PL8a171akLsinNTlNdNp1Equp9Yy8c6DrZ",
                    "https://www.youtube.com/watch?v=t60roHM1t7o&list=PL8a171akLsikDai5OoaKg3VPsKQkF7_Ic",
                    "https://www.youtube.com/watch?v=9cSmgHBNWxc&list=PL8a171akLsikR8IRL32jC6RQAj1K6sgD9",
                    "https://www.youtube.com/watch?v=ssdgFoHLwnk&list=PL8a171akLsinwEvFL6xArd7u6Yhd-G_CY",
                    "https://www.youtube.com/watch?v=u5CVsCnxyXg&list=PL8a171akLsimjBNGSVuu-RGJw9eXL_r3W"],
    Kickass: ["https://www.youtube.com/watch?v=dTaD9cd8hvw&list=PL8a171akLsinZVjDBN9wScZjcJ2nEr3YU",
                    "https://www.youtube.com/watch?v=ePSR7gFt7s4&list=PL8a171akLsikhFBlpDOhonaGO0HlABxxt",
                    "https://www.youtube.com/watch?v=t5jaRipA5_M&list=PL8a171akLsimimVQE7a7F34t5C6GBF2f4",
                    "https://www.youtube.com/watch?v=4vwRjHHQQ4k&list=PL8a171akLsilyx63OEhcKB8zlcO0xcPa-",
                    "https://www.youtube.com/watch?v=bU8h44NUoiM&list=PL8a171akLsineA_cubG2RTYQOHU3cpBSZ",
                    "https://www.youtube.com/watch?v=BSJ8rDlBZ_I&list=PL8a171akLsintYdsB7qR2r-vKMtB93o1a",
                    "https://www.youtube.com/watch?v=MuJYZpdIjc0&list=PL8a171akLsimnYmwtzOLOd0w0a5cgkubS",
                    "https://www.youtube.com/watch?v=pwT9G6t-SKI&list=PL8a171akLsikdmUBpAxf5isxeSTIeA2En",
                    "https://www.youtube.com/watch?v=gJRdFAoVDQA&list=PL8a171akLsikHXROw1jLR3HBSSAKn_kdE",
                    "https://www.youtube.com/watch?v=_ltir3dUO40&list=PL8a171akLsikDRSYB2K38tGxFuiw6w5Os"],
    House: ["https://www.youtube.com/watch?v=-NdffntOACY",
                    "https://www.youtube.com/watch?v=dMkk9UG96W4",
                    "https://www.youtube.com/watch?v=xLV9vJLsczs",
                    "https://www.youtube.com/watch?v=XTwzY5jjrbU",
                    "https://www.youtube.com/watch?v=goS2DyWcCqc",
                    "https://www.youtube.com/watch?v=FjSfJ0RcVms",
                    "https://www.youtube.com/watch?v=nXjsFiEbO8E",
                    "https://www.youtube.com/watch?v=_-482McoVIE",
                    "https://www.youtube.com/watch?v=WwVM_GfVtBY",
                    "https://www.youtube.com/watch?v=ryf3zwUX8WY",
                    "https://www.youtube.com/watch?v=anoeiupmK4Q",
                    "https://www.youtube.com/watch?v=xSH84m5ktUw",
                    "https://www.youtube.com/watch?v=bk6Xst6euQk",
                    "https://www.youtube.com/watch?v=W4u2ba2B1ww",
                    "https://www.youtube.com/watch?v=8tULfknjHvo",
                    "https://www.youtube.com/watch?v=GA2dvXs-olc",
                    "https://www.youtube.com/watch?v=IDVeCfQCIds",
                    "https://www.youtube.com/watch?v=C_vUwvBbsPg",
                    "https://www.youtube.com/watch?v=LYSXYk9Em_E",
                    "https://www.youtube.com/watch?v=5vHRUsP20dQ"],
    Electronic: ["https://www.youtube.com/watch?v=oqLoW5XE2bs&list=PL8a171akLsimvRBQMoSsHn63Hrw_gJU4-",
                    "https://www.youtube.com/watch?v=Vwyh32REroQ&list=PL8a171akLsikh-bOeHKZkSTNJUObhv_KT",
                    "https://www.youtube.com/watch?v=0Z4cLmbw6q0&list=PL8a171akLsim_wqfCt2BAR-3JiCvRPXnL",
                    "https://www.youtube.com/watch?v=MBFXJw7n-fU&list=PL8a171akLsikX9n_8_rStiQk21L-xVM6x",
                    "https://www.youtube.com/watch?v=k2ugG2gapUM&list=PL8a171akLsimE_sTndox5gEBgl1WLS9FU",
                    "https://www.youtube.com/watch?v=TaXqU7hVVhI&list=PL8a171akLsinMbSU7oy3B2z-jK5-hwzpo",
                    "https://www.youtube.com/watch?v=DKCpIi4Azns&list=PL8a171akLsim5SyFSGfdP2_qo-Ap5pa9S",
                    "https://www.youtube.com/watch?v=CC409Aqc3l4&list=PL8a171akLsilJ1cFjQ1OfjG2PPrg_Vuya",
                    "https://www.youtube.com/watch?v=tyy6TTzAYpA&list=PL8a171akLsiltPw7gdLgdWKv7AcZ-9eeu",
                    "https://www.youtube.com/watch?v=xH5MpGDKsGg&list=PL8a171akLsimxkq5Nt9by2y8igr4arcvc"]


}